name: data_manager_sylph_tax_database
owner: bgruening
description: "Download sylph-tax taxonomy metadata files"
homepage_url: "https://github.com/bluenote-1577/sylph-tax"
remote_repository_url: "https://github.com/bgruening/galaxytools/tree/master/data_managers/data_manager_sylph_tax_database"
type: unrestricted
categories:
- Data Managers