name: qiime2_dbotu_q2
owner: bgruening
description: q2-dbotu is a Qiime 2 plugin for performing OTU clustering
homepage_url: https://github.com/cduvallet/q2-dbotu/tree/master
long_description: |
  q2-dbotu is a Qiime 2 plugin for performing OTU clustering using the distribution-based OTU (dbOTU) algorithm.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/qiime2_dbotu_q2/
type: unrestricted
categories:
- Metagenomics